org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true

org.gradle.tooling.parallel=true

GROUP=mobi.parchment
VERSION_NAME=2.0.0-SNAPSHOT
POM_ARTIFACT_ID=parchment
POM_NAME=Parchment
POM_DESCRIPTION=Horizontal/Vertical ListView, GridView, ViewPager, and GridPatternView for Android
POM_URL=https://github.com/TinkerNorth/parchment
POM_SCM_URL=https://github.com/TinkerNorth/parchment
POM_SCM_CONNECTION=scm:git:git://github.com/TinkerNorth/parchment.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/TinkerNorth/parchment.git
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=emir-hasanbegovic
POM_DEVELOPER_NAME=Emir Hasanbegovic
