android.useAndroidX=true

# Library coordinates
GROUP=mobi.parchment
VERSION_NAME=2.0.0
POM_ARTIFACT_ID=parchment
POM_NAME=Parchment
POM_DESCRIPTION=Horizontal/Vertical ListView, GridView, ViewPager, and GridPatternView for Android
POM_URL=https://github.com/EmirWeb/parchment
POM_SCM_URL=https://github.com/EmirWeb/parchment
POM_SCM_CONNECTION=scm:git:git://github.com/EmirWeb/parchment.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/EmirWeb/parchment.git
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=EmirWeb
POM_DEVELOPER_NAME=Emir Hasanbegovic

